version: '3.9'
services:
  api:
    build: ./backend_api
    image: is_this_nestle_api
    container_name: isThisNestle_api
    volumes:
      - ./data:/code/app/backend/data
    ports:
      - "1274:5000"

  webapp:
    build: ./frontend
    image: is_this_nestle_webapp
    container_name: isThisNestle_webapp
    ports:
      - "1338:80"
    depends_on:
      - api